import Foundation

enum ExperimentRegistry {
    static let all: [ExperimentDescriptor] = [
        ExperimentDescriptor(id: "localauthentication", name: "LocalAuthentication", category: .security,
            description: "Test Face ID, Touch ID, or device-owner authentication and inspect real failure states.",
            frameworks: ["LocalAuthentication"], supportedPlatforms: SupportedPlatform.allCases,
            hardwareRequirements: ["Face ID or Touch ID when biometrics are tested"], osRequirements: ["iOS 11+ · macOS 10.13+ · watchOS 4+ · tvOS 11+"],
            permissions: ["Biometric/device authentication prompt"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/localauthentication")!, evaluate: { .available }),
        ExperimentDescriptor(id: "cryptokit", name: "CryptoKit", category: .security,
            description: "Hash data, create a P-256 key, sign a message, and verify the signature in one live run.",
            frameworks: ["CryptoKit"], supportedPlatforms: SupportedPlatform.allCases,
            hardwareRequirements: [], osRequirements: ["iOS 13+ · macOS 10.15+ · watchOS 6+ · tvOS 13+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit")!, evaluate: { .available }),
        ExperimentDescriptor(id: "keychain", name: "Keychain", category: .security,
            description: "Write, read, and delete a generic password item using the public Keychain API.",
            frameworks: ["Security"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 2+ · macOS 10.6+"], permissions: [], capabilities: ["Data Protection"], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/security/keychain_services")!, evaluate: { .available }),
        ExperimentDescriptor(id: "secure-enclave", name: "Secure Enclave", category: .security,
            description: "Create a non-exportable signing key, expose its public key, and verify a signature.",
            frameworks: ["CryptoKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Secure Enclave"], osRequirements: ["iOS 11+ · macOS 10.14+ · watchOS 4+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit/storing-keys-in-the-secure-enclave")!, evaluate: { DeviceCapabilities.current.secureEnclave ? .available : .hardwareUnsupported }),
        ExperimentDescriptor(id: "core-location", name: "Core Location", category: .location,
            description: "Request permission and inspect live coordinates, accuracy, altitude, speed, and course.",
            frameworks: ["CoreLocation"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Location hardware or a simulated location"], osRequirements: ["iOS 6+ · macOS 10.9+ · watchOS 2+"], permissions: ["Location When In Use"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/corelocation")!, evaluate: { .permissionRequired }),
        ExperimentDescriptor(id: "core-motion", name: "Core Motion", category: .sensors,
            description: "Stream device motion with user acceleration, rotation rate, and gravity values.",
            frameworks: ["CoreMotion"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["Motion sensors"], osRequirements: ["iOS 7+ · watchOS 2+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/coremotion")!, evaluate: { DeviceCapabilities.current.motion ? .available : .hardwareUnsupported }),
        ExperimentDescriptor(id: "core-nfc", name: "Core NFC", category: .nfc,
            description: "Read NDEF tags and inspect their records with a real NFC reader session.", frameworks: ["CoreNFC"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["NFC-capable iPhone or iPad"], osRequirements: ["iOS 11+"], permissions: ["NFC Reader Usage Description"], capabilities: ["Near Field Communication"], entitlements: ["Near Field Communication Tag Reading"], documentationURL: URL(string: "https://developer.apple.com/documentation/corenfc")!, evaluate: { CurrentPlatform.value == .iOS || CurrentPlatform.value == .iPadOS ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "core-bluetooth", name: "Core Bluetooth", category: .connectivity,
            description: "Scan for nearby Bluetooth Low Energy peripherals and inspect identifiers and signal strength.", frameworks: ["CoreBluetooth"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Bluetooth hardware"], osRequirements: ["iOS 5+ · macOS 10.9+ · watchOS 4+"], permissions: ["Bluetooth Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/corebluetooth")!, evaluate: { .available }),
        ExperimentDescriptor(id: "network-path", name: "Network Path", category: .networking,
            description: "Monitor live connectivity, available interfaces, cost, and constrained-network state.", frameworks: ["Network"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 10.14+ · watchOS 5+ · tvOS 12+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/network")!, evaluate: { .available }),
        ExperimentDescriptor(id: "camera-vision", name: "Camera & Vision", category: .camera,
            description: "Capture live camera frames and run Vision text recognition on the real image stream.", frameworks: ["AVFoundation", "Vision"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Camera"], osRequirements: ["iOS 11+ · macOS 10.15+"], permissions: ["Camera Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/vision")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "audio-input", name: "Audio Input", category: .audio,
            description: "Open the microphone and inspect live input channels, sample rate, and RMS level.", frameworks: ["AVFAudio", "AVFoundation"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 12+ · macOS 10.15+"], permissions: ["Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/avfaudio")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "mapkit-search", name: "MapKit Search", category: .maps,
            description: "Search real map data for places and inspect returned names and coordinates.", frameworks: ["MapKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 6+ · macOS 10.9+ · tvOS 9+"], permissions: [], capabilities: ["Maps"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/mapkit")!, evaluate: { [.iOS, .iPadOS, .macOS, .tvOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "homekit-discovery", name: "HomeKit Discovery", category: .home,
            description: "Discover homes, rooms, and accessories through the public HomeKit home manager.", frameworks: ["HomeKit"], supportedPlatforms: [.iOS, .iPadOS, .watchOS, .tvOS], hardwareRequirements: ["HomeKit home or simulator"], osRequirements: ["iOS 8+ · watchOS 2+ · tvOS 10+"], permissions: ["HomeKit access"], capabilities: ["HomeKit"], entitlements: ["HomeKit"], documentationURL: URL(string: "https://developer.apple.com/documentation/homekit")!, evaluate: { [.iOS, .iPadOS, .watchOS, .tvOS].contains(CurrentPlatform.value) ? .permissionRequired : .platformUnsupported }),
        ExperimentDescriptor(id: "matter-status", name: "Matter Status", category: .home,
            description: "Inspect whether the Matter framework is present and explain commissioning requirements.", frameworks: ["Matter"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: ["Matter accessory for commissioning"], osRequirements: ["Current Apple OS with Matter support"], permissions: [], capabilities: ["Matter"], entitlements: ["Matter Allow Setup Payload"], documentationURL: URL(string: "https://developer.apple.com/documentation/matter")!, evaluate: { .approvalRequired }),
        ExperimentDescriptor(id: "continuity", name: "WatchConnectivity", category: .connectivity,
            description: "Activate the public WatchConnectivity session and inspect reachability.", frameworks: ["WatchConnectivity"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Apple Watch pairing for reachability"], osRequirements: ["iOS 9+ · watchOS 2+ · macOS 10.15+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/watchconnectivity")!, evaluate: { [.iOS, .iPadOS, .macOS, .watchOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "app-intents", name: "App Intents", category: .developer,
            description: "Expose a small real App Intent that can be discovered by Siri and Shortcuts.", frameworks: ["AppIntents"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: [], osRequirements: ["Current Apple OS with App Intents support"], permissions: [], capabilities: ["Siri"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/appintents")!, evaluate: { .available }),
        ExperimentDescriptor(id: "natural-language", name: "Natural Language", category: .ai,
            description: "Run real on-device language identification and inspect confidence hypotheses.", frameworks: ["NaturalLanguage"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 10.14+ · watchOS 5+ · tvOS 12+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/naturallanguage")!, evaluate: { .available }),
        ExperimentDescriptor(id: "foundation-models", name: "Foundation Models", category: .ai,
            description: "Inspect public Foundation Models framework and explain real availability conditions.", frameworks: ["FoundationModels"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Apple Intelligence-capable device where required"], osRequirements: ["Supported current OS and region"], permissions: [], capabilities: ["Apple Intelligence"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/foundationmodels")!, evaluate: { .available }),
        ExperimentDescriptor(id: "healthkit-status", name: "HealthKit Status", category: .developer,
            description: "Check HealthKit availability and explain its authorization and entitlement boundary.", frameworks: ["HealthKit"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["Health-capable device"], osRequirements: ["iOS 8+ · watchOS 2+"], permissions: ["HealthKit authorization"], capabilities: ["HealthKit"], entitlements: ["HealthKit"], documentationURL: URL(string: "https://developer.apple.com/documentation/healthkit")!, evaluate: { [.iOS, .iPadOS, .watchOS].contains(CurrentPlatform.value) ? .permissionRequired : .platformUnsupported }),
        ExperimentDescriptor(id: "wallet-status", name: "Wallet & PassKit", category: .wallet,
            description: "Inspect PassKit availability and the passes visible to this app.", frameworks: ["PassKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["Current OS with PassKit support"], permissions: [], capabilities: ["Wallet"], entitlements: ["Wallet for advanced credentials"], documentationURL: URL(string: "https://developer.apple.com/documentation/passkit")!, evaluate: { [.iOS, .iPadOS, .macOS, .tvOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "widgetkit", name: "WidgetKit", category: .developer,
            description: "Inspect the native WidgetKit extension included with the iOS app and its timeline-driven entry point.", frameworks: ["WidgetKit", "SwiftUI"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: [], osRequirements: ["iOS 14+ · iPadOS 14+"], permissions: [], capabilities: ["Home Screen Widgets"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/widgetkit")!, evaluate: { [.iOS, .iPadOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "nearby-interaction", name: "Nearby Interaction / UWB", category: .connectivity,
            description: "Inspect Nearby Interaction device capabilities and prepare a real peer-ranging session using discovery tokens.", frameworks: ["NearbyInteraction"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["UWB-capable peer devices for precise ranging"], osRequirements: ["iOS 16+ · iPadOS 16+ · watchOS 9+"], permissions: [], capabilities: ["Nearby Interaction", "Ultra Wideband"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/nearbyinteraction")!, evaluate: { [.iOS, .iPadOS, .watchOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "indoor-imdf", name: "Indoor Maps / IMDF", category: .maps,
            description: "Import a real Indoor Mapping Data Format JSON file and inspect its feature collections without inventing map data.", frameworks: ["Foundation", "MapKit concepts"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 14+ · macOS 11+"], permissions: ["User-selected file access"], capabilities: ["Indoor Maps", "File Provider access"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/mapkit/indoor_maps")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "arkit", name: "ARKit", category: .camera,
            description: "Start real world tracking and inspect whether the device supports scene-depth frames.", frameworks: ["ARKit"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["ARKit-capable camera and motion hardware"], osRequirements: ["iOS 11+ · iPadOS 11+"], permissions: ["Camera Usage Description"], capabilities: ["ARKit", "Scene Depth where supported"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/arkit")!, evaluate: { [.iOS, .iPadOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "roomplan", name: "RoomPlan", category: .camera,
            description: "Inspect RoomPlan support and the hardware boundary for room-capture experiments.", frameworks: ["RoomPlan"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["LiDAR-capable device for full capture"], osRequirements: ["iOS 16+ · iPadOS 16+"], permissions: ["Camera Usage Description"], capabilities: ["RoomPlan", "LiDAR"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/roomplan")!, evaluate: { [.iOS, .iPadOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "speech", name: "Speech Recognition", category: .ai,
            description: "Use the real speech recognizer and microphone to transcribe live spoken words.", frameworks: ["Speech", "AVFAudio"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 10+ · macOS 10.15+"], permissions: ["Speech Recognition", "Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/speech")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .permissionRequired : .platformUnsupported })
        ,ExperimentDescriptor(id: "core-ml", name: "Core ML", category: .ai,
            description: "Inspect the Core ML integration boundary and require a real model before inference.", frameworks: ["CoreML"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 11+ · macOS 10.13+"], permissions: [], capabilities: ["Neural Engine where available"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/coreml")!, evaluate: { .available })
        ,ExperimentDescriptor(id: "translation", name: "Translation", category: .ai,
            description: "Inspect platform translation requirements without claiming language support that has not been verified.", frameworks: ["Translation"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["Current supported OS"], permissions: [], capabilities: ["On-device language resources"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/translation")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "sound-analysis", name: "Sound Analysis", category: .audio,
            description: "Inspect the SoundAnalysis model boundary for future real-time audio classification.", frameworks: ["SoundAnalysis"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone for live classification"], osRequirements: ["iOS 13+ · macOS 10.15+"], permissions: ["Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/soundanalysis")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
    ]

    static func descriptor(for id: String) -> ExperimentDescriptor? { all.first { $0.id == id } }
}
