import Foundation

enum ExperimentRegistry {
    static let all: [ExperimentDescriptor] = [
        ExperimentDescriptor(id: "localauthentication", name: "LocalAuthentication", category: .security,
            description: "Test Face ID, Touch ID, or device-owner authentication and inspect real failure states.",
            frameworks: ["LocalAuthentication"], supportedPlatforms: [.iOS, .iPadOS, .macOS],
            hardwareRequirements: ["Face ID or Touch ID when biometrics are tested"], osRequirements: ["iOS 11+ · macOS 10.13+"],
            permissions: ["Biometric/device authentication prompt"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/localauthentication")!, evaluate: ExperimentAvailability.localAuthentication),
        ExperimentDescriptor(id: "cryptokit", name: "CryptoKit", category: .security,
            description: "Hash data, create a P-256 key, sign a message, and verify the signature in one live run.",
            frameworks: ["CryptoKit"], supportedPlatforms: SupportedPlatform.allCases,
            hardwareRequirements: [], osRequirements: ["iOS 13+ · macOS 10.15+ · watchOS 6+ · tvOS 13+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit")!, evaluate: { .available }),
        ExperimentDescriptor(id: "keychain", name: "Keychain", category: .security,
            description: "Write, read, and delete a generic password item using the public Keychain API.",
            frameworks: ["Security"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 2+ · macOS 10.6+"], permissions: [], capabilities: ["Data Protection"], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/security/keychain_services")!, evaluate: { .available }),
        ExperimentDescriptor(id: "secure-enclave", name: "Secure Enclave", category: .security,
            description: "Create a non-exportable signing key, expose its public key, and verify a signature.",
            frameworks: ["CryptoKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Secure Enclave"], osRequirements: ["iOS 11+ · macOS 10.14+ · watchOS 4+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit/storing-keys-in-the-secure-enclave")!, evaluate: { DeviceCapabilities.current.secureEnclave ? .available : .hardwareUnsupported }),
        ExperimentDescriptor(id: "core-location", name: "Core Location", category: .location,
            description: "Inspect live coordinates, precise vs. approximate accuracy, heading and floor, and monitor a region, visits, and significant changes around you.",
            frameworks: ["CoreLocation"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Location hardware or a simulated location", "Magnetometer for heading"], osRequirements: ["iOS 6+ · macOS 10.9+ · watchOS 2+", "CLMonitor: iOS 17+ · macOS 14+"], permissions: ["Location When In Use", "Temporary precise location (purpose key)", "Location Always (optional upgrade for visits and significant changes)"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/corelocation")!, evaluate: ExperimentAvailability.location),
        ExperimentDescriptor(id: "core-motion", name: "Core Motion", category: .sensors,
            description: "Stream device motion with user acceleration, rotation rate, and gravity values.",
            frameworks: ["CoreMotion"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["Motion sensors"], osRequirements: ["iOS 7+ · watchOS 2+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/coremotion")!, evaluate: { DeviceCapabilities.current.motion ? .available : .hardwareUnsupported }),
        ExperimentDescriptor(id: "core-nfc", name: "Core NFC", category: .nfc,
            description: "Read NDEF tags and inspect their records with a real NFC reader session.", frameworks: ["CoreNFC"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["NFC-capable iPhone or iPad"], osRequirements: ["iOS 11+"], permissions: ["NFC Reader Usage Description"], capabilities: ["Near Field Communication"], entitlements: ["Near Field Communication Tag Reading"], documentationURL: URL(string: "https://developer.apple.com/documentation/corenfc")!, evaluate: ExperimentAvailability.nfc),
        ExperimentDescriptor(id: "core-bluetooth", name: "Core Bluetooth", category: .connectivity,
            description: "Scan for nearby Bluetooth Low Energy peripherals and inspect identifiers and signal strength.", frameworks: ["CoreBluetooth"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Bluetooth hardware"], osRequirements: ["iOS 5+ · macOS 10.9+ · watchOS 4+"], permissions: ["Bluetooth Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/corebluetooth")!, evaluate: ExperimentAvailability.bluetooth),
        ExperimentDescriptor(id: "multipeer-connectivity", name: "MultipeerConnectivity", category: .connectivity,
            description: "Discover nearby Apple Toolbox devices, connect them automatically, and exchange live messages over a local peer-to-peer session.", frameworks: ["MultipeerConnectivity"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Wi-Fi or Bluetooth for nearby peer discovery"], osRequirements: ["iOS 7+ · macOS 10.10+"], permissions: ["Local Network Usage Description"], capabilities: ["Local peer-to-peer networking"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/multipeerconnectivity")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "network-path", name: "Network Path", category: .networking,
            description: "Monitor live connectivity, available interfaces, cost, and constrained-network state.", frameworks: ["Network"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 10.14+ · watchOS 5+ · tvOS 12+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/network")!, evaluate: { .available }),
        ExperimentDescriptor(id: "camera-vision", name: "Camera & Vision", category: .camera,
            description: "Capture live camera frames and run Vision text recognition on the real image stream.", frameworks: ["AVFoundation", "Vision"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Camera"], osRequirements: ["iOS 11+ · macOS 10.15+"], permissions: ["Camera Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/vision")!, evaluate: ExperimentAvailability.camera),
        ExperimentDescriptor(id: "audio-input", name: "Audio Input", category: .audio,
            description: "Open the microphone and inspect live input channels, sample rate, and RMS level.", frameworks: ["AVFAudio", "AVFoundation"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 12+ · macOS 10.15+"], permissions: ["Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/avfaudio")!, evaluate: ExperimentAvailability.microphone),
        ExperimentDescriptor(id: "mapkit-search", name: "MapKit Search", category: .maps,
            description: "Search real map data for places and inspect returned names and coordinates.", frameworks: ["MapKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 6+ · macOS 10.9+ · tvOS 9+"], permissions: [], capabilities: ["Maps"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/mapkit")!, evaluate: { [.iOS, .iPadOS, .macOS, .tvOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
        ExperimentDescriptor(id: "homekit-discovery", name: "HomeKit Discovery", category: .home,
            description: "Discover homes, rooms, and accessories through the public HomeKit home manager.", frameworks: ["HomeKit"], supportedPlatforms: [.iOS, .iPadOS, .watchOS, .tvOS], hardwareRequirements: ["HomeKit home or simulator"], osRequirements: ["iOS 8+ · watchOS 2+ · tvOS 10+"], permissions: ["HomeKit access"], capabilities: ["HomeKit"], entitlements: ["HomeKit"], documentationURL: URL(string: "https://developer.apple.com/documentation/homekit")!, evaluate: ExperimentAvailability.homeKit),
        ExperimentDescriptor(id: "matter-status", name: "Matter Accessory Setup", category: .home,
            description: "Start Apple Home's accessory setup flow to commission a Matter accessory into a home, then inspect the returned home and accessory identifiers or the real error.", frameworks: ["HomeKit"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["Matter accessory with its setup code"], osRequirements: ["iOS 15.4+ · iPadOS 15.4+"], permissions: [], capabilities: ["HomeKit", "Matter"], entitlements: ["com.apple.developer.homekit"], documentationURL: URL(string: "https://developer.apple.com/documentation/homekit/hmaccessorysetupmanager")!, evaluate: ExperimentAvailability.matterSetup),
        ExperimentDescriptor(id: "continuity", name: "WatchConnectivity", category: .connectivity,
            description: "Activate the public WatchConnectivity session and inspect reachability.", frameworks: ["WatchConnectivity"], supportedPlatforms: [.iOS, .watchOS], hardwareRequirements: ["Apple Watch pairing for reachability"], osRequirements: ["iOS 9+ · watchOS 2+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/watchconnectivity")!, evaluate: ExperimentAvailability.watchConnectivity),
        ExperimentDescriptor(id: "app-intents", name: "App Intents", category: .developer,
            description: "Run the app's App Intents in-process (status, SHA-256 hash, capability summary, open a category or experiment) and list the App Shortcuts registered for Siri, Spotlight, and Shortcuts.", frameworks: ["AppIntents", "CryptoKit"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 16+ · macOS 13+ · watchOS 9+ · tvOS 16+"], permissions: [], capabilities: ["App Shortcuts (no Siri entitlement needed)", "App entities and queries"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/appintents")!, evaluate: { .available }),
        ExperimentDescriptor(id: "natural-language", name: "Natural Language", category: .ai,
            description: "Run real on-device language identification and inspect confidence hypotheses.", frameworks: ["NaturalLanguage"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 10.14+ · watchOS 5+ · tvOS 12+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/naturallanguage")!, evaluate: { .available }),
        ExperimentDescriptor(id: "foundation-models", name: "Foundation Models", category: .ai,
            description: "Read the on-device model's availability and concrete reason, stream a reply to your own prompt, and generate a typed @Generable result with guided generation.", frameworks: ["FoundationModels"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Apple Intelligence-capable device"], osRequirements: ["iOS 26+ · macOS 26+ with Apple Intelligence enabled"], permissions: [], capabilities: ["Apple Intelligence", "On-device language model"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/foundationmodels")!, evaluate: ExperimentAvailability.foundationModels),
        ExperimentDescriptor(id: "healthkit-status", name: "HealthKit Status", category: .developer,
            description: "Check HealthKit availability and explain its authorization and entitlement boundary.", frameworks: ["HealthKit"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["Health-capable device"], osRequirements: ["iOS 8+ · watchOS 2+"], permissions: ["HealthKit authorization"], capabilities: ["HealthKit"], entitlements: ["HealthKit"], documentationURL: URL(string: "https://developer.apple.com/documentation/healthkit")!, evaluate: ExperimentAvailability.healthKit),
        ExperimentDescriptor(id: "wallet-status", name: "Wallet & PassKit", category: .wallet,
            description: "Inspect PassKit availability and the passes visible to this app.", frameworks: ["PassKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["Current OS with PassKit support"], permissions: [], capabilities: ["Wallet"], entitlements: ["Wallet for advanced credentials"], documentationURL: URL(string: "https://developer.apple.com/documentation/passkit")!, evaluate: ExperimentAvailability.wallet)
        ,ExperimentDescriptor(id: "wallet-creator", name: "Wallet Pass Creator", category: .wallet,
            description: "Create and export a real pass.json draft. An installable Apple Wallet pass still requires Apple signing credentials.", frameworks: ["PassKit", "Foundation"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 6+ · macOS 10.9+"], permissions: ["User-selected export destination"], capabilities: ["Wallet pass format"], entitlements: ["Pass Type ID certificate for installable .pkpass"], documentationURL: URL(string: "https://developer.apple.com/documentation/walletpasses")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .approvalRequired : .platformUnsupported })
        ,ExperimentDescriptor(id: "widgetkit", name: "WidgetKit", category: .developer,
            description: "Share the last opened experiment with the Home Screen and Lock Screen widget through an App Group, list the installed widget configurations, and reload their timelines.", frameworks: ["WidgetKit", "SwiftUI", "Foundation"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: [], osRequirements: ["iOS 18+ · iPadOS 18+"], permissions: [], capabilities: ["Home Screen widgets", "Lock Screen widgets", "App Groups"], entitlements: ["com.apple.security.application-groups"], documentationURL: URL(string: "https://developer.apple.com/documentation/widgetkit")!, evaluate: ExperimentAvailability.widgetKit)
        ,ExperimentDescriptor(id: "nearby-interaction", name: "Nearby Interaction / UWB", category: .connectivity,
            description: "Inspect Nearby Interaction device capabilities and prepare a real peer-ranging session using discovery tokens.", frameworks: ["NearbyInteraction"], supportedPlatforms: [.iOS, .iPadOS, .watchOS], hardwareRequirements: ["UWB-capable peer devices for precise ranging"], osRequirements: ["iOS 16+ · iPadOS 16+ · watchOS 9+"], permissions: [], capabilities: ["Nearby Interaction", "Ultra Wideband"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/nearbyinteraction")!, evaluate: ExperimentAvailability.nearbyInteraction)
        ,ExperimentDescriptor(id: "indoor-imdf", name: "Indoor Maps / IMDF", category: .maps,
            description: "Import a real Indoor Mapping Data Format JSON file and inspect its feature collections without inventing map data.", frameworks: ["Foundation", "MapKit concepts"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 14+ · macOS 11+"], permissions: ["User-selected file access"], capabilities: ["Indoor Maps", "File Provider access"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/mapkit/indoor_maps")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "arkit", name: "ARKit", category: .camera,
            description: "Start real world tracking and inspect whether the device supports scene-depth frames.", frameworks: ["ARKit"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["ARKit-capable camera and motion hardware"], osRequirements: ["iOS 11+ · iPadOS 11+"], permissions: ["Camera Usage Description"], capabilities: ["ARKit", "Scene Depth where supported"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/arkit")!, evaluate: ExperimentAvailability.arKit)
        ,ExperimentDescriptor(id: "roomplan", name: "RoomPlan", category: .camera,
            description: "Inspect RoomPlan support and the hardware boundary for room-capture experiments.", frameworks: ["RoomPlan"], supportedPlatforms: [.iOS, .iPadOS], hardwareRequirements: ["LiDAR-capable device for full capture"], osRequirements: ["iOS 16+ · iPadOS 16+"], permissions: ["Camera Usage Description"], capabilities: ["RoomPlan", "LiDAR"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/roomplan")!, evaluate: ExperimentAvailability.roomPlan)
        ,ExperimentDescriptor(id: "speech", name: "Speech Recognition", category: .ai,
            description: "Use the real speech recognizer and microphone to transcribe live spoken words.", frameworks: ["Speech", "AVFAudio"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 10+ · macOS 10.15+"], permissions: ["Speech Recognition", "Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/speech")!, evaluate: ExperimentAvailability.speech)
        ,ExperimentDescriptor(id: "core-ml", name: "Core ML", category: .ai,
            description: "List the CPU, GPU and Neural Engine Core ML can use, then import a .mlmodel, .mlpackage or .mlmodelc, compile it on device and inspect its inputs, outputs, metadata and compute units. No inference is run.", frameworks: ["CoreML", "Metal"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 17+ · macOS 14+"], permissions: ["User-selected file access"], capabilities: ["On-device model compilation", "Neural Engine where available"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/coreml")!, evaluate: { .available })
        ,ExperimentDescriptor(id: "translation", name: "Translation", category: .ai,
            description: "Pick a language pair from the languages the system supports, check whether it is installed, supported or unsupported, and translate your own text with a real TranslationSession.", frameworks: ["Translation", "SwiftUI"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 18+ · macOS 15+"], permissions: [], capabilities: ["On-device language assets", "Language download (network)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/translation")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported })
        ,ExperimentDescriptor(id: "sound-analysis", name: "Sound Analysis", category: .audio,
            description: "Classify live microphone audio with Apple's built-in sound classifier and watch the top three labels and their confidence update in real time.", frameworks: ["SoundAnalysis", "AVFAudio"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 15+ · macOS 12+"], permissions: ["Microphone Usage Description"], capabilities: ["Built-in sound classifier (version 1)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/soundanalysis")!, evaluate: ExperimentAvailability.microphone)
        ,ExperimentDescriptor(id: "musickit", name: "MusicKit", category: .audio,
            description: "Request real MusicKit authorization without pretending that a user account or library is available.", frameworks: ["MusicKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: [], osRequirements: ["Current supported OS"], permissions: ["Apple Music authorization"], capabilities: ["Apple Music"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/musickit")!, evaluate: ExperimentAvailability.musicKit)
        ,ExperimentDescriptor(id: "shazamkit", name: "ShazamKit", category: .audio,
            description: "Create a real ShazamKit session and expose the audio-matching boundary.", frameworks: ["ShazamKit"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone and audio source"], osRequirements: ["iOS 15+ · macOS 12+"], permissions: ["Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/shazamkit")!, evaluate: ExperimentAvailability.microphone)
        ,ExperimentDescriptor(id: "notifications", name: "UserNotifications", category: .developer,
            description: "Request notification authorization and schedule one real local test notification.", frameworks: ["UserNotifications"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 10+ · macOS 10.14+ · watchOS 3+ · tvOS 10+"], permissions: ["Notification authorization"], capabilities: ["Alerts, sounds, badges"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/usernotifications")!, evaluate: ExperimentAvailability.notifications)
        ,ExperimentDescriptor(id: "app-attest", name: "App Attest & DeviceCheck", category: .security,
            description: "Generate and attest a Secure Enclave key, sign a sample payload with an assertion, and request a DeviceCheck token. The challenge is local; server-side verification is out of scope.", frameworks: ["DeviceCheck", "CryptoKit"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: ["A physical device that supports App Attest (not the Simulator)"], osRequirements: ["App Attest: iOS 14+ · macOS 11+ · tvOS 15+ · watchOS 9+", "DeviceCheck: iOS 11+ · macOS 10.15+ · tvOS 11+ · watchOS 9+"], permissions: [], capabilities: ["App ID registered with Apple", "App Attest capability optional (development builds use the sandbox without it)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/devicecheck/establishing-your-app-s-integrity")!, evaluate: ExperimentAvailability.appAttest)
        ,ExperimentDescriptor(id: "passkeys", name: "Passkeys", category: .security,
            description: "Send a real passkey registration or assertion request for a relying party you enter and inspect the credential or the system's error. Challenges are local random bytes.", frameworks: ["AuthenticationServices"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 15+ · macOS 12+ · tvOS 16+"], permissions: [], capabilities: ["Associated Domains with a webcredentials: entry", "apple-app-site-association file on the relying-party domain"], entitlements: ["com.apple.developer.associated-domains (webcredentials:)"], documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/supporting-passkeys")!, evaluate: ExperimentAvailability.passkeys)
        ,ExperimentDescriptor(id: "sign-in-with-apple", name: "Sign in with Apple", category: .security,
            description: "Run the real Sign in with Apple flow, inspect the returned credential (shortened identifier, real-user status, token and code sizes) and query its credential state.", frameworks: ["AuthenticationServices"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 13+ · macOS 10.15+ · tvOS 13+ · watchOS 6+"], permissions: [], capabilities: ["Sign in with Apple", "Apple Account signed in on the device"], entitlements: ["com.apple.developer.applesignin"], documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/implementing-user-authentication-with-sign-in-with-apple")!, evaluate: ExperimentAvailability.signInWithApple)
        ,ExperimentDescriptor(id: "capability-explorer", name: "Capability Explorer", category: .developer,
            description: "Scan this device with public APIs: hardware, sensors, cameras, display, and Apple features, each reported as available, unavailable, or unknown without triggering a permission prompt.", frameworks: ["Device capability APIs", "CoreMotion", "CoreLocation", "AVFoundation", "LocalAuthentication", "NearbyInteraction", "FoundationModels"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["Current Apple OS"], permissions: [], capabilities: ["Device and framework inspection"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/bundleresources/entitlements")!, evaluate: { .available })
        ,ExperimentDescriptor(id: "game-controller", name: "Game Controller", category: .input,
            description: "List connected game controllers and the Siri Remote with profile, battery, and haptics, discover wireless controllers, and watch live button, trigger, and stick input.", frameworks: ["GameController"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: ["Connected game controller (Siri Remote on Apple TV)"], osRequirements: ["iOS 14+ · macOS 11+ · tvOS 14+"], permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/gamecontroller")!, evaluate: ExperimentAvailability.gameController)
    ]

    static func descriptor(for id: String) -> ExperimentDescriptor? { all.first { $0.id == id } }
}
