import Foundation

extension ExperimentRegistry {
    static let security: [ExperimentDescriptor] = [
        ExperimentDescriptor(id: "localauthentication", name: "LocalAuthentication", category: .security,
            description: "Inspect the biometry type, every LocalAuthentication policy with its live result and error code, and enrolment changes through the domain state; evaluate a policy with a reuse window and authorize LARight and LAPersistedRight.",
            frameworks: ["LocalAuthentication"], supportedPlatforms: [.iOS, .iPadOS, .macOS],
            hardwareRequirements: ["Face ID, Touch ID or Optic ID when biometrics are tested", "Paired Mac, Apple Vision Pro or Apple Watch for companion policies"],
            osRequirements: ["iOS 11+ · macOS 10.13+", "Domain state and companion policies: iOS 18+ · macOS 15+", "LARight and LAPersistedRight: iOS 16+ · macOS 13+"],
            permissions: ["Biometric/device authentication prompt (only from the Evaluate and Authorize buttons)"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/localauthentication")!, evaluate: ExperimentAvailability.localAuthentication,
            useCase: ExperimentUseCase(id: "biometric-gate", title: "Protect an action and notice enrolment changes", summary: "Gate an action behind a LocalAuthentication policy or an LARight, and detect when the enrolled faces or fingerprints changed.", interaction: "Open the experiment to compare the domain state with the last check, then evaluate a policy or authorize a right and inspect the real outcome."),
            explanations: [
                .unavailable: ExperimentExplanation(reason: "No device passcode is set, so owner authentication cannot run.", required: "A device passcode (and optionally Face ID or Touch ID)",
                    nextStep: "Set a passcode in Settings › Face ID & Passcode."),
                .hardwareUnsupported: ExperimentExplanation(reason: "Neither biometrics nor passcode authentication can be evaluated here.", required: "Face ID, Touch ID or a device passcode",
                    nextStep: "Run on a device with a passcode; in the Simulator enroll Face ID via Features › Face ID."),
            ]),
        ExperimentDescriptor(id: "cryptokit", name: "CryptoKit Lab", category: .security,
            description: "Hash, authenticate, encrypt, agree on keys, sign and seal with HPKE on your own text, and generate, export and import keys. Every run checks the round trip and shows that tampered data is rejected.",
            frameworks: ["CryptoKit"], supportedPlatforms: SupportedPlatform.allCases,
            hardwareRequirements: [], osRequirements: ["iOS 13+ · macOS 10.15+ · watchOS 6+ · tvOS 13+", "HPKE: iOS 17+ · macOS 14+ · tvOS 17+ · watchOS 10+", "X-Wing HPKE: iOS 26+ · macOS 26+ · tvOS 26+ · watchOS 26+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit")!, evaluate: { .available },
            useCase: ExperimentUseCase(id: "crypto-lab", title: "Credential / Crypto Lab", summary: "Use CryptoKit as a working crypto bench: SHA-2 and HMAC, AES-GCM and ChaChaPoly, ECDH with HKDF, ECDSA and Ed25519, HPKE, and key export/import as raw, X9.63, DER and PEM.", interaction: "Pick an operation and algorithm, enter your message, and run it; for keys, export a new one and import it again or paste your own.")),
        ExperimentDescriptor(id: "keychain", name: "Keychain", category: .security,
            description: "Write, read, and delete a generic password, and store one behind SecAccessControl so reading it needs Face ID, Touch ID, or the passcode.",
            frameworks: ["Security", "LocalAuthentication"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 2+ · macOS 10.6+", "Access control: iOS 11.3+ · macOS 10.13.4+"], permissions: ["Face ID, Touch ID or passcode prompt (protected item)"], capabilities: ["Data Protection"], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/security/keychain_services")!, evaluate: { .available },
            useCase: ExperimentUseCase(id: "keychain-value", title: "Store a secret", summary: "Use the Keychain as a small persistent credential store and lock one item behind Face ID, Touch ID, or the passcode.", interaction: "Save, read, and delete a plain value; then pick a protection, save a protected item, and read it back through the real authentication prompt.")),
        ExperimentDescriptor(id: "secure-enclave", name: "Secure Enclave", category: .security,
            description: "Create a non-exportable signing key, keep it across runs through its Keychain blob, sign and verify, and delete it again.",
            frameworks: ["CryptoKit", "Security", "LocalAuthentication"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS], hardwareRequirements: ["Secure Enclave"], osRequirements: ["iOS 11+ · macOS 10.14+ · watchOS 4+"], permissions: ["Face ID, Touch ID or passcode prompt (keys that require user presence)"], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/cryptokit/storing-keys-in-the-secure-enclave")!, evaluate: { DeviceCapabilities.current.secureEnclave ? .available : .hardwareUnsupported },
            useCase: ExperimentUseCase(id: "secure-enclave-signature", title: "Sign with hardware-backed storage", summary: "Keep a non-exportable Secure Enclave key across launches and sign your own message with it.", interaction: "Sign with the persistent key to see whether it was created or reused and compare its fingerprint; delete it to start over. The private key never leaves the enclave."),
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "This device or simulator does not provide a Secure Enclave, so keys can be neither created nor restored.", required: "A device with a Secure Enclave (iPhone 5s or later, Apple silicon or T2 Mac, Apple Watch)",
                    nextStep: "Run the experiment on a physical device."),
            ]),
        ExperimentDescriptor(id: "app-attest", name: "App Attest & DeviceCheck", category: .security,
            description: "Generate and attest a Secure Enclave key, sign a sample payload with an assertion, and request a DeviceCheck token. The challenge is local; server-side verification is out of scope.", frameworks: ["DeviceCheck", "CryptoKit"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: ["A physical device that supports App Attest (not the Simulator)"], osRequirements: ["App Attest: iOS 14+ · macOS 11+ · tvOS 15+ · watchOS 9+", "DeviceCheck: iOS 11+ · macOS 10.15+ · tvOS 11+ · watchOS 9+"], permissions: [], capabilities: ["App ID registered with Apple", "App Attest capability optional (development builds use the sandbox without it)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/devicecheck/establishing-your-app-s-integrity")!, evaluate: ExperimentAvailability.appAttest,
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "DCAppAttestService reports that App Attest is not supported here (for example in the Simulator).", required: "A physical device with a Secure Enclave and an App ID registered with Apple",
                    nextStep: "Run the experiment on a real device; the DeviceCheck token can still be tried below."),
            ],
            applePrograms: ["Apple Developer Program: App Attest needs a registered App ID"]),
        ExperimentDescriptor(id: "passkeys", name: "Passkeys", category: .security,
            description: "Send a real passkey registration or assertion request for a relying party you enter and inspect the credential or the system's error. Challenges are local random bytes.", frameworks: ["AuthenticationServices"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 15+ · macOS 12+ · tvOS 16+"], permissions: [], capabilities: ["Associated Domains with a webcredentials: entry", "apple-app-site-association file on the relying-party domain"], entitlements: ["com.apple.developer.associated-domains (webcredentials:)"], documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/supporting-passkeys")!, evaluate: ExperimentAvailability.passkeys,
            explanations: [
                .entitlementRequired: ExperimentExplanation(reason: "Passkeys are bound to a relying-party domain, and no webcredentials: associated domain is provisioned for this app.", required: "Associated Domains entitlement with webcredentials:<domain> and an apple-app-site-association file on that domain listing this app",
                    nextStep: "Add the Associated Domains capability for your relying party and host the association file. The requests below still run and show the system's rejection."),
            ],
            applePrograms: ["Apple Developer Program: Associated Domains are not available to free Personal Teams"]),
        ExperimentDescriptor(id: "sign-in-with-apple", name: "Sign in with Apple", category: .security,
            description: "Run the real Sign in with Apple flow, inspect the returned credential (shortened identifier, real-user status, token and code sizes) and query its credential state.", frameworks: ["AuthenticationServices"], supportedPlatforms: SupportedPlatform.allCases, hardwareRequirements: [], osRequirements: ["iOS 13+ · macOS 10.15+ · tvOS 13+ · watchOS 6+"], permissions: [], capabilities: ["Sign in with Apple", "Apple Account signed in on the device"], entitlements: ["com.apple.developer.applesignin"], documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/implementing-user-authentication-with-sign-in-with-apple")!, evaluate: ExperimentAvailability.signInWithApple,
            explanations: [
                .entitlementRequired: ExperimentExplanation(reason: "Neither the embedded provisioning profile nor this build's readable signed entitlements include Sign in with Apple.", required: "com.apple.developer.applesignin = [Default], enabled on the App ID of a paid developer team",
                    nextStep: "Add the Sign in with Apple capability to this target in Xcode › Signing & Capabilities; the button below still shows the system's real error."),
            ],
            applePrograms: ["Apple Developer Program: Sign in with Apple is not available to free Personal Teams"]),
        ExperimentDescriptor(id: "keychain-sharing", name: "Keychain Sharing & iCloud Keychain", category: .security,
            description: "Save, read and delete an item in the app's own, a team-shared or the App Group keychain access group, list every item the app can see per group, and mark items as iCloud Keychain synchronizable.",
            frameworks: ["Security"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: [], osRequirements: ["Access groups: iOS 3+ · macOS 10.9+ · tvOS 9+", "Synchronizable items: iOS 7+ · macOS 10.9+ · tvOS 9+", "macOS: data protection keychain, 10.15+"], permissions: [], capabilities: ["Keychain Sharing", "App Groups", "iCloud Keychain turned on by the person (synchronizable items)"], entitlements: ["keychain-access-groups", "com.apple.security.application-groups"],
            documentationURL: URL(string: "https://developer.apple.com/documentation/security/sharing-access-to-keychain-items-among-a-collection-of-apps")!, evaluate: ExperimentAvailability.keychainSharing,
            useCase: ExperimentUseCase(id: "shared-credential", title: "Share a credential between your apps", summary: "Put a secret into a keychain access group that other apps of the same team can read, optionally synced through iCloud Keychain.", interaction: "Check the access groups, pick one, save and read an item, and list what the app can see in each group."),
            explanations: [
                .entitlementRequired: ExperimentExplanation(reason: "This build declares no keychain-access-groups entitlement, so it can only use its default access group.", required: "The Keychain Sharing capability listing $(AppIdentifierPrefix)\(ToolboxIdentifiers.base).shared (the iOS target has it)",
                    nextStep: "Add Keychain Sharing under Signing & Capabilities for this target. The buttons below still run and show errSecMissingEntitlement for the shared group."),
            ]),
        ExperimentDescriptor(id: "security-keys", name: "Security Keys (WebAuthn)", category: .security,
            description: "Register and use a FIDO2 security key over USB, NFC or Lightning with ASAuthorizationSecurityKeyPublicKeyCredentialProvider for a relying party you enter, with user verification, attestation and discoverable-credential choices. Challenges are local random bytes.",
            frameworks: ["AuthenticationServices"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["A FIDO2 / WebAuthn security key (USB, NFC or Lightning)"], osRequirements: ["iOS 15+ · macOS 12+", "Reported transports and AppID flag: iOS 17.5+ · macOS 14.5+"], permissions: [], capabilities: ["Associated Domains with a webcredentials: entry", "apple-app-site-association file on the relying-party domain"], entitlements: ["com.apple.developer.associated-domains (webcredentials:)"],
            documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialprovider")!, evaluate: ExperimentAvailability.securityKeys,
            useCase: ExperimentUseCase(id: "security-key-login", title: "Sign in with a hardware key", summary: "Use a phishing-resistant FIDO2 security key as a second factor or passwordless credential for your relying party.", interaction: "Enter the relying-party domain, choose the WebAuthn options, register the key, then sign in with it."),
            explanations: [
                .entitlementRequired: ExperimentExplanation(reason: "Security key credentials are bound to a relying-party domain, and no webcredentials: associated domain is provisioned for this app.", required: "Associated Domains entitlement with webcredentials:<domain> and an apple-app-site-association file on that domain listing this app",
                    nextStep: "Add the Associated Domains capability for your relying party and host the association file. The requests below still run and show the system's rejection."),
            ],
            applePrograms: ["Apple Developer Program: Associated Domains are not available to free Personal Teams"]),
        ExperimentDescriptor(id: "credential-provider", name: "AutoFill Credential Provider", category: .security,
            description: "A real AutoFill credential provider: the iOS app bundles an ASCredentialProviderViewController extension that fills demo passwords and creates and signs demo passkeys from the App Group vault. The app shows the live ASCredentialIdentityStore state, saves and removes identities, and asks to be turned on.",
            frameworks: ["AuthenticationServices"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 11+", "Settings shortcut: iOS 17+ · macOS 14+", "Turn-on request: iOS 18+ · macOS 15+"], permissions: [], capabilities: ["Credential provider app extension (ASCredentialProviderViewController), passwords and passkeys", "Turned on by the person in Settings › General › AutoFill & Passwords", "App Group shared with the extension"], entitlements: ["com.apple.developer.authentication-services.autofill-credential-provider (app and extension)", "com.apple.security.application-groups"],
            documentationURL: URL(string: "https://developer.apple.com/documentation/authenticationservices/ascredentialidentitystore")!, evaluate: ExperimentAvailability.credentialProvider,
            useCase: ExperimentUseCase(id: "autofill-provider", title: "Offer your credentials in AutoFill", summary: "Turn Apple Toolbox on as a password manager and let it fill demo passwords and create and use demo passkeys in Safari and apps.", interaction: "Create the demo passwords, turn the provider on, save the identities, then tap a password field on example.com. On a WebAuthn test site, choose Apple Toolbox to save a passkey and sign in with it."),
            explanations: [
                .entitlementRequired: ExperimentExplanation(reason: "This build bundles no credential provider extension whose provisioning profile carries the AutoFill Credential Provider entitlement. The extension ships only in the iOS app, so the Mac app has none.", required: "The AppleToolbox Credential Provider extension (iOS) with com.apple.developer.authentication-services.autofill-credential-provider on the app and extension App IDs",
                    nextStep: "Enable AutoFill Credential Provider and the App Group for the app and extension App IDs and install a new iOS build. The buttons below still run and show the store's real state and errors."),
            ]),
    ]
}
