import Foundation

extension ExperimentRegistry {
    static let ai: [ExperimentDescriptor] = [
        ExperimentDescriptor(id: "natural-language", name: "Natural Language", category: .ai,
            description: "Identify the language, tokenize by word, sentence or paragraph, tag lexical classes and named entities, score sentiment, lemmatize, and compare words or sentences with the bundled NLEmbedding models, all on device.", frameworks: ["NaturalLanguage"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .watchOS, .tvOS], hardwareRequirements: [], osRequirements: ["iOS 12+ · macOS 10.14+ · watchOS 5+ · tvOS 12+ (sentiment iOS 13+, sentence embeddings iOS 14+)"], permissions: [], capabilities: ["On-device language models", "Tagger asset download (network)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/naturallanguage")!, evaluate: { .available }),
        ExperimentDescriptor(id: "foundation-models", name: "Foundation Models", category: .ai,
            description: "Read the on-device model's availability and concrete reason, stream a reply to your own prompt, and generate a typed @Generable result with guided generation.", frameworks: ["FoundationModels"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Apple Intelligence-capable device"], osRequirements: ["iOS 26+ · macOS 26+ with Apple Intelligence enabled"], permissions: [], capabilities: ["Apple Intelligence", "On-device language model"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/foundationmodels")!, evaluate: ExperimentAvailability.foundationModels,
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "This device is not eligible for Apple Intelligence.", required: "An Apple Intelligence-capable device",
                    nextStep: "Run on a device that supports Apple Intelligence."),
                .unavailable: ExperimentExplanation(reason: "Apple Intelligence is turned off (appleIntelligenceNotEnabled) or the model is still downloading (modelNotReady); the run section shows which.", required: "Apple Intelligence enabled with the model downloaded",
                    nextStep: "Turn on Apple Intelligence in Settings › Apple Intelligence & Siri and wait for the model download to finish."),
            ]),
        ExperimentDescriptor(id: "foundation-models-tools", name: "Foundation Models Tools & Context", category: .ai,
            description: "Hold a multi-turn conversation in one LanguageModelSession whose model can call two app tools (device capabilities from the scanner, experiment catalog search), inspect the transcript, count tokens against the context size, and see context-overflow, guardrail and language errors as the framework reports them.", frameworks: ["FoundationModels"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Apple Intelligence-capable device"], osRequirements: ["iOS 26.4+ · macOS 26.4+ with Apple Intelligence enabled (token counts need 26.4)"], permissions: [], capabilities: ["Apple Intelligence", "On-device language model", "Tool calling"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/foundationmodels/expanding-generation-with-tool-calling")!, evaluate: ExperimentAvailability.foundationModels,
            useCase: ExperimentUseCase(id: "foundation-models-tools-chat", title: "Let the model call your code",
                summary: "Ask about this device or the app's experiments; the model decides when to call the Swift tools and answers from their real output. The transcript and token count grow with every turn.",
                interaction: "Choose the tools, send a message, follow up in the same session, and try the oversized prompt to hit the context limit."),
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "This device is not eligible for Apple Intelligence.", required: "An Apple Intelligence-capable device",
                    nextStep: "Run on a device that supports Apple Intelligence."),
                .unavailable: ExperimentExplanation(reason: "Apple Intelligence is turned off (appleIntelligenceNotEnabled) or the model is still downloading (modelNotReady).", required: "Apple Intelligence enabled with the model downloaded",
                    nextStep: "Turn on Apple Intelligence in Settings › Apple Intelligence & Siri and wait for the model download to finish."),
                .platformUnsupported: ExperimentExplanation(reason: "The FoundationModels module can be imported on tvOS and watchOS, but LanguageModelSession and SystemLanguageModel are unavailable there.", required: "iOS, iPadOS or macOS 26.4+",
                    nextStep: "Open the experiment on iPhone, iPad or Mac."),
            ]),
        ExperimentDescriptor(id: "speech", name: "Speech Recognition", category: .ai,
            description: "Use the real speech recognizer and microphone to transcribe live spoken words.", frameworks: ["Speech", "AVFAudio"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["Microphone"], osRequirements: ["iOS 10+ · macOS 10.15+"], permissions: ["Speech Recognition", "Microphone Usage Description"], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/speech")!, evaluate: ExperimentAvailability.speech),
        ExperimentDescriptor(id: "speech-analyzer", name: "SpeechAnalyzer", category: .ai,
            description: "Transcribe the microphone live or a picked audio file with SpeechAnalyzer and SpeechTranscriber, watch volatile results turn into finalized text, and manage the locale's model assets with AssetInventory.", frameworks: ["Speech", "AVFAudio"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: ["SpeechTranscriber-capable device", "Microphone for live transcription"], osRequirements: ["iOS 26+ · macOS 26+"], permissions: ["Microphone Usage Description", "User-selected file access"], capabilities: ["On-device speech-to-text", "Speech model assets (download)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/speech/speechanalyzer")!, evaluate: ExperimentAvailability.speechAnalyzer,
            useCase: ExperimentUseCase(id: "speech-analyzer-live", title: "Live and file transcription",
                summary: "Speak and see SpeechTranscriber's volatile guesses replaced by finalized text with timings, or transcribe an audio file. Audio never leaves the device; only the model is downloaded once per locale.",
                interaction: "Pick a locale, download its assets if needed, then start live transcription or choose an audio file."),
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "SpeechTranscriber.isAvailable is false: this device's hardware cannot run the SpeechTranscriber model.", required: "A device that supports SpeechTranscriber",
                    nextStep: "Use the Speech Recognition experiment (SFSpeechRecognizer) on this device, or run SpeechAnalyzer on a newer iPhone, iPad or Mac."),
                .permissionDenied: ExperimentExplanation(reason: "Microphone access was denied, so live transcription cannot start. File transcription still works.", required: "Microphone Usage Description",
                    nextStep: "Allow the microphone in Settings › Privacy & Security › Microphone, or transcribe an audio file."),
                .platformUnsupported: ExperimentExplanation(reason: "SpeechAnalyzer is unavailable on watchOS, and Apple TV offers neither microphone input for apps nor a document picker.", required: "iOS, iPadOS or macOS 26",
                    nextStep: "Open the experiment on iPhone, iPad or Mac."),
            ]),
        ExperimentDescriptor(id: "core-ml", name: "Core ML", category: .ai,
            description: "List the CPU, GPU and Neural Engine Core ML can use, compile a model trained on this device with Create ML or an imported .mlmodel, .mlpackage or .mlmodelc, inspect it, then run real predictions and compare load and prediction times for each compute-unit setting with MLComputePlan's device choice.", frameworks: ["CoreML", "Metal"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 17.4+ · macOS 14.4+ (MLComputePlan)"], permissions: ["User-selected file access", "Photo picker (no permission needed)"], capabilities: ["On-device model compilation", "On-device inference", "Neural Engine where available"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/coreml")!, evaluate: { .available },
            useCase: ExperimentUseCase(id: "core-ml-benchmark", title: "Run your own model on every compute unit",
                summary: "Load the model you just trained with Create ML, give it text, numbers or a photo, and see its output plus load time, first and median prediction time for CPU only, CPU & GPU, CPU & Neural Engine and All.",
                interaction: "Pick a trained model or import one, fill in the inputs, choose the repetitions and compare all compute units."),
            explanations: [
                .platformUnsupported: ExperimentExplanation(reason: "Importing a model needs the system document picker, which Apple TV and Apple Watch do not offer; watchOS also cannot compile models on device.", required: "iOS, iPadOS or macOS",
                    nextStep: "Open the experiment on iPhone, iPad or Mac. On Apple TV the compute devices are still listed below."),
            ]),
        ExperimentDescriptor(id: "create-ml", name: "Create ML", category: .ai,
            description: "Train a text classifier or tabular regressor from a CSV, or an image or sound classifier from your own photos and audio files grouped by label, on this device with the Create ML framework; compare training and validation metrics, run the new model on your own input and export the .mlmodel.", frameworks: ["CreateML", "TabularData", "PhotosUI"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 15+ on a device · macOS 11+"], permissions: ["User-selected file access", "Photo picker (no permission needed)"], capabilities: ["On-device model training", "Model export (share sheet)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/createml")!, evaluate: ExperimentAvailability.createML,
            useCase: ExperimentUseCase(id: "create-ml-train", title: "Train a model in seconds",
                summary: "Label a few sentences, rows of numbers, photos or sound clips, train with MLTextClassifier, a regressor, MLImageClassifier or MLSoundClassifier on device, and see how well it generalizes to the held-out validation samples.",
                interaction: "Pick the task, edit the CSV or add labels with photos or audio files, train, try the model on new input, then share the .mlmodel or benchmark it in the Core ML experiment."),
            explanations: [
                .deviceOnly: ExperimentExplanation(reason: "CreateML.framework is part of the iOS device SDK but missing from the iOS Simulator SDK, so a Simulator build contains no Create ML code.", required: "A physical iPhone or iPad, or a Mac",
                    nextStep: "Run Apple Toolbox on a device or on the Mac to train."),
                .platformUnsupported: ExperimentExplanation(reason: "watchOS has no Create ML framework. On tvOS the text, image and sound classifiers are unavailable and there is no document or photo picker for training data.", required: "iOS, iPadOS or macOS",
                    nextStep: "Open the experiment on iPhone, iPad or Mac."),
            ]),
        ExperimentDescriptor(id: "translation", name: "Translation", category: .ai,
            description: "Pick a language pair from the languages the system supports, check whether it is installed, supported or unsupported, and translate your own text with a real TranslationSession.", frameworks: ["Translation", "SwiftUI"], supportedPlatforms: [.iOS, .iPadOS, .macOS], hardwareRequirements: [], osRequirements: ["iOS 18+ · macOS 15+"], permissions: [], capabilities: ["On-device language assets", "Language download (network)"], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/translation")!, evaluate: { [.iOS, .iPadOS, .macOS].contains(CurrentPlatform.value) ? .available : .platformUnsupported }),
    ]
}
