import Foundation

extension ExperimentRegistry {
    static let platform: [ExperimentDescriptor] = [
        ExperimentDescriptor(id: "metal", name: "Metal", category: .platform,
            description: "Inspect the system Metal GPU (architecture, GPU families, unified memory, recommended working set, ray tracing, threadgroup limits, argument buffer tier), then compile a compute kernel from source at runtime that doubles an array on the GPU and verify every value.",
            frameworks: ["Metal"], supportedPlatforms: [.iOS, .iPadOS, .macOS, .tvOS], hardwareRequirements: ["Metal GPU"],
            osRequirements: ["iOS 8+ · macOS 10.11+ · tvOS 9+", "GPU families: iOS 13+ · macOS 10.15+ · tvOS 13+", "Metal 4 family: iOS 26+ · macOS 26+ · tvOS 26+"],
            permissions: [], capabilities: [], entitlements: [], documentationURL: URL(string: "https://developer.apple.com/documentation/metal")!, evaluate: ExperimentAvailability.metal,
            useCase: ExperimentUseCase(id: "metal-compute", title: "Run your own code on the GPU", summary: "See what the GPU reports about itself, then prove it runs code: a kernel is compiled from source on this device and doubles 4,096 floats.", interaction: "Read the GPU facts and families, then run the compute check and compare the verified values and GPU time."),
            explanations: [
                .hardwareUnsupported: ExperimentExplanation(reason: "MTLCreateSystemDefaultDevice() returned nil, so this device exposes no Metal GPU to apps.", required: "A Metal GPU (every supported iPhone, iPad, Apple TV and Mac has one)",
                    nextStep: "Run the experiment on the device itself; some virtual machines and remote sessions expose no Metal device."),
                .platformUnsupported: ExperimentExplanation(reason: "watchOS has no Metal framework; apps draw only through SwiftUI and SpriteKit there.", required: "iOS, iPadOS, macOS or tvOS",
                    nextStep: "Open Apple Toolbox on an iPhone, iPad, Mac or Apple TV."),
            ]),
        ExperimentDescriptor(id: "mac-hardware", name: "Mac Hardware", category: .platform,
            description: "List Core Audio devices with transport, channels and sample rates, cameras including Continuity Camera, mounted volumes with capacity, APFS, encryption and case sensitivity, and connected displays with resolution, refresh rate and EDR headroom. Public APIs only, no IOKit.",
            frameworks: ["CoreAudio", "AVFoundation", "Foundation", "AppKit", "CoreGraphics"], supportedPlatforms: [.macOS], hardwareRequirements: [],
            osRequirements: ["macOS 10.15+", "External and Continuity cameras: macOS 14+"], permissions: [], capabilities: ["App Sandbox: device and volume metadata only, no recording"], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/coreaudio")!, evaluate: ExperimentAvailability.macHardware,
            useCase: ExperimentUseCase(id: "mac-hardware-inventory", title: "Inventory the Mac's hardware", summary: "See every audio device, camera, drive and display the system reports, with the formats and capabilities apps can rely on.", interaction: "Read the lists, then turn on Watch for Changes and plug in headphones, a drive or a display."),
            explanations: [
                .platformUnsupported: ExperimentExplanation(reason: "The Core Audio hardware layer (AudioObject), NSScreen and mounted-volume enumeration only exist on macOS. iOS and iPadOS expose audio routes through AVAudioSession and screens through UIScreen instead.", required: "macOS",
                    nextStep: "Open Apple Toolbox on a Mac, or use Audio Input, Windows & Displays and the Capability Explorer here."),
            ]),
        ExperimentDescriptor(id: "apple-pencil", name: "Apple Pencil", category: .platform,
            description: "Draw on a PencilKit canvas with the tool picker and read every touch live: force, altitude, azimuth and barrel roll, coalesced and predicted touches, Pencil hover distance and tilt, and double-tap and squeeze with the actions chosen in Settings.",
            frameworks: ["PencilKit", "UIKit"], supportedPlatforms: [.iPadOS], hardwareRequirements: ["iPad with a compatible Apple Pencil", "Hover: M2 iPad or later with Apple Pencil (2nd generation, USB-C or Pro)", "Squeeze and barrel roll: Apple Pencil Pro"],
            osRequirements: ["iPadOS 13+ (PencilKit)", "Hover distance: iPadOS 16.1+", "Squeeze, barrel roll: iPadOS 17.5+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/pencilkit")!, evaluate: ExperimentAvailability.applePencil,
            useCase: ExperimentUseCase(id: "pencil-telemetry", title: "See what Apple Pencil tells an app", summary: "Every stroke carries pressure and tilt, hover reports distance above the screen, and double-tap and squeeze arrive as interactions.", interaction: "Draw with Apple Pencil, hover above the canvas, then double-tap or squeeze and watch the readouts."),
            explanations: [
                .platformUnsupported: ExperimentExplanation(reason: "Apple Pencil pairs only with iPad. The PencilKit canvas below still works with a finger on iPhone, but pressure, tilt, hover, double-tap and squeeze never arrive; macOS has no PKCanvasView.", required: "iPadOS and a compatible Apple Pencil",
                    nextStep: "Open Apple Toolbox on an iPad and pair Apple Pencil in Settings › Apple Pencil."),
            ]),
        ExperimentDescriptor(id: "pointer-keyboard", name: "Pointer & Keyboard", category: .platform,
            description: "Track hover location with onContinuousHover, try hover effects (pointer styles on the Mac), read hardware key presses and modifier state with onKeyPress (onModifierKeysChanged on the Mac), and compare them with raw GCKeyboard and GCMouse input.",
            frameworks: ["SwiftUI", "GameController"], supportedPlatforms: [.iPadOS, .iOS, .macOS], hardwareRequirements: ["Hardware keyboard, mouse or trackpad (built in on a Mac)"],
            osRequirements: ["iPadOS 17+ · macOS 14+ (onKeyPress)", "macOS 15+ (live modifier keys, pointer style and visibility)", "GCKeyboard, GCMouse: iPadOS 14+ · macOS 11+"], permissions: [], capabilities: [], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/swiftui/view/onkeypress(phases:action:)")!, evaluate: ExperimentAvailability.pointerKeyboard,
            useCase: ExperimentUseCase(id: "input-inspector", title: "Inspect keyboard and pointer input", summary: "See which keys, modifiers and pointer movements reach the app, both through SwiftUI events and as raw GameController input.", interaction: "Start monitoring, hover over the pad, tap it to give it keyboard focus, then type and hold modifier keys."),
            explanations: [
                .unavailable: ExperimentExplanation(reason: "GameController reports no hardware keyboard, mouse or trackpad connected to this device.", required: "A Magic Keyboard, Smart Keyboard Folio, Bluetooth keyboard, mouse or trackpad",
                    nextStep: "Attach or pair one; it appears here as soon as GameController reports it. iPhone accepts keyboards but shows no pointer."),
                .platformUnsupported: ExperimentExplanation(reason: "Apple TV and Apple Watch have no hardware keyboard or pointer input for apps.", required: "iPadOS, iOS or macOS",
                    nextStep: "Use the Game Controller experiment for the Siri Remote, or open Apple Toolbox on an iPad or Mac."),
            ]),
        ExperimentDescriptor(id: "windows-displays", name: "Windows & Displays", category: .platform,
            description: "Follow the window scene live: size classes, window and screen size, orientation, size restrictions, open sessions and the screens scenes are on (resolution, refresh rate, EDR, mirroring), and open a second window with openWindow.",
            frameworks: ["UIKit", "SwiftUI"], supportedPlatforms: [.iPadOS, .iOS], hardwareRequirements: ["Multiple windows: iPad", "External display: a USB-C or AirPlay display"],
            osRequirements: ["iPadOS 16+ (effectiveGeometry)", "iPadOS 26+ (window coordinate space, interactive resizing)"], permissions: [], capabilities: ["UIApplicationSupportsMultipleScenes (generated scene manifest)"], entitlements: [],
            documentationURL: URL(string: "https://developer.apple.com/documentation/uikit/uiwindowscene")!, evaluate: ExperimentAvailability.windowsDisplays,
            useCase: ExperimentUseCase(id: "window-geometry", title: "Watch the window change", summary: "See how iPadOS sizes this window, which size classes the layout gets, and which screens the app's scenes are on.", interaction: "Resize the window or rotate the iPad, open a second window, or connect an external display."),
            explanations: [
                .platformUnsupported: ExperimentExplanation(reason: "Size classes, window scenes and UIScreen are iPadOS and iOS concepts. Mac windows are native AppKit windows, and Apple TV and Apple Watch run one full-screen interface.", required: "iPadOS or iOS",
                    nextStep: "Open Apple Toolbox on an iPad. On a Mac, Mac Hardware lists the connected displays."),
            ]),
    ]
}
